<a href="https://colab.research.google.com/github/woodstone10/data-intelligence-lab/blob/main/prediction_comparison.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Prediction Models Accurary Comparison

---
- Logistic Regression
- Random Forest
- Neural Network
- Gaussian NB
- Decision Tree Classifier
- SVM


In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
import sklearn.model_selection
import sklearn.preprocessing
import sklearn.metrics
import sklearn.linear_model
import sklearn.ensemble
import sklearn.neural_network
import sklearn.naive_bayes
import sklearn.tree
import sklearn.svm

## Data

In [ ]:
a = pd.read_csv('https://raw.githubusercontent.com/woodstone10/dataset/main/adult.data', sep= ',', header= None,skiprows=1)
b = pd.read_csv('https://raw.githubusercontent.com/woodstone10/dataset/main/adult.test', sep= ',', header= None,skiprows=1)
df = pd.concat([a, b])
df.head()

0                  1       2           3   ...  11  12              13      14
0  50   Self-emp-not-inc   83311   Bachelors  ...   0  13   United-States   <=50K
1  38            Private  215646     HS-grad  ...   0  40   United-States   <=50K
2  53            Private  234721        11th  ...   0  40   United-States   <=50K
3  28            Private  338409   Bachelors  ...   0  40            Cuba   <=50K
4  37            Private  284582     Masters  ...   0  40   United-States   <=50K

[5 rows x 15 columns]

In [ ]:
data = df
data.replace({
    ' <=50K':0,
    ' <=50K.':0,
    ' >50K':1,
    ' >50K.':1,
},inplace=True)
print(data.head())

   0                  1       2           3   ...  11  12              13 14
0  50   Self-emp-not-inc   83311   Bachelors  ...   0  13   United-States  0
1  38            Private  215646     HS-grad  ...   0  40   United-States  0
2  53            Private  234721        11th  ...   0  40   United-States  0
3  28            Private  338409   Bachelors  ...   0  40            Cuba  0
4  37            Private  284582     Masters  ...   0  40   United-States  0

[5 rows x 15 columns]


encoding using sklearn LabelEncoder (string to numeric)

In [ ]:
transform_needed = [False, True, False, True, False, True, True, True, True, True, False, False, False, True, False]
encoded_data = np.zeros(shape=(data.shape[0], data.shape[1]), dtype=np.int)
for i in range(len(transform_needed)):
    if transform_needed[i]:
        tmp_data = data.iloc[:, i].tolist()
        encoder = sklearn.preprocessing.LabelEncoder()
        encoder.fit(tmp_data)
        encoded_data[:, i] = encoder.transform(tmp_data)
    else:
        encoded_data[:, i] = data.iloc[:, i].tolist()
print(encoded_data)

[[    50      6  83311 ...     13     39      0]
 [    38      4 215646 ...     40     39      0]
 [    53      4 234721 ...     40     39      0]
 ...
 [    38      4 374983 ...     50     39      0]
 [    44      4  83891 ...     40     39      0]
 [    35      5 182148 ...     60     39      1]]


encoded data X and y

In [ ]:
X = encoded_data[:,:14]
y = encoded_data[:,14]
print(X)

[[    50      6  83311 ...      0     13     39]
 [    38      4 215646 ...      0     40     39]
 [    53      4 234721 ...      0     40     39]
 ...
 [    38      4 374983 ...      0     50     39]
 [    44      4  83891 ...      0     40     39]
 [    35      5 182148 ...      0     60     39]]


encoded data split into train 80%, test 20%

In [ ]:
X_train, X_test, y_train, y_test = sklearn.model_selection.train_test_split(X, y, test_size=0.2)
print("total data size:",X.shape, "train data size:",X_train.shape, "test data size:",X_test.shape)


total data size: (48841, 14) train data size: (39072, 14) test data size: (9769, 14)


## Model comparison

In [ ]:
# Model. Logistic Regression
model = sklearn.linear_model.LogisticRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
test_acc = sklearn.metrics.accuracy_score(y_test, y_pred)
print("Logistic Regression:",test_acc)

# Model. Random Forest
model = sklearn.ensemble.RandomForestClassifier()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
test_acc = sklearn.metrics.accuracy_score(y_test, y_pred)
print("Random Forest:",test_acc)

# Model. Neural Network
model = sklearn.neural_network.MLPClassifier()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
test_acc = sklearn.metrics.accuracy_score(y_test, y_pred)
print("Neural Network:",test_acc)

# Model. Naive Bayes
model = sklearn.naive_bayes.GaussianNB()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
test_acc = sklearn.metrics.accuracy_score(y_test, y_pred)
print("Gaussian NB:",test_acc)

# Model. Decision Tree
model = sklearn.tree.DecisionTreeClassifier()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
test_acc = sklearn.metrics.accuracy_score(y_test, y_pred)
print("Decision Tree Classifier:",test_acc)

# Model. SVM
model = sklearn.svm.SVC()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
test_acc = sklearn.metrics.accuracy_score(y_test, y_pred)
print("SVM:",test_acc)

Logistic Regression: 0.7871839492271471
Random Forest: 0.8582249974408844


/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


Neural Network: 0.569249667314976
Gaussian NB: 0.7918927218753199
Decision Tree Classifier: 0.8121609171870202
SVM: 0.7951683898044836
